# Generated by Django 4.2.7 on 2023-12-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_advertisement_photo4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='number_phone',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
